[package]
name = "ar-edit"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["tui"]
tui = ["dep:ratatui", "dep:crossterm"]

[dependencies]
ar-edit-core.workspace = true
clap.workspace = true
ratatui = { workspace = true, optional = true }
crossterm = { workspace = true, optional = true }
notify.workspace = true
indicatif.workspace = true
tokio.workspace = true
anyhow.workspace = true
clap_complete.workspace = true
serde.workspace = true
serde_json.workspace = true
ratatui-image = { version = "4", default-features = false, features = ["crossterm"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }

[dev-dependencies]
assert_cmd.workspace = true
tempfile.workspace = true
