[package]
name = "ar-edit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ar-edit-core.workspace = true
clap.workspace = true
ratatui.workspace = true
crossterm.workspace = true
notify.workspace = true
indicatif.workspace = true
tokio.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
tempfile.workspace = true
