when:
  - event: [push, pull_request]

steps:
  - name: test
    image: rust:1-bookworm
    commands:
      - rustup component add rustfmt clippy
      - cargo test --all --verbose
      - cargo fmt --all -- --check
      - cargo clippy --all -- -D warnings
